name: Build and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: npm install
      - name: Build
        run: npm run build
      - name: Zip output
        uses: vimtor/action-zip@v1.1
        with:
          files: .output ecosystem.config.js
          dest: build_result.zip
      - name: Copy build_result.zip to vultr
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build_result.zip
          remote: /root/frontend/build_result.zip
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Extract zip file
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            rm -rf /root/frontend/build_result
            unzip /root/frontend/build_result.zip -d /root/frontend/build_result
      - run: echo "🍏 This job's status is ${{ job.status }}."
